name: Run Emotion Engine

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install yfinance pandas numpy matplotlib fredapi

      - name: Run engine
        run: |
          python emotion_engine.py
